- hosts: all
  # gather_facts: smart
  remote_user: root
  roles:
    - { role: apt, become: true }
    - { role: atom.io }
    - { role: zsh }
    - { role: docker, become: yes }
    - { role: git }
    - { role: font }
    - { role: gsetting }
    - { role: autostart }

  vars_prompt:
    - name: "gitconfig_user_name"
      prompt: "what is your gitconfig user.name"
      private: no

    - name: "gitconfig_user_email"
      prompt: "what is your gitconfig user.email"
      private: no
