- name: Create autostart directory
  file: path=~/.config/autostart state=directory mode=0755

- name: Add autostart files
  template: src="app.desktop.j2" dest="~/.config/autostart/{{ item.key }}.desktop"
  with_dict: "{{applications}}"
