repositories:
  - ppa:webupd8team/atom
  - ppa:pinta-maintainers/pinta-stable
  - ppa:kilian/f.lux
packages:
  - atom
  - git
  - gitg
  - zsh
  - apt-transport-https
  - ca-certificates
  - pinta
  - fluxgui
