- name: clone oh-my-zsh git repository
  git: repo=https://github.com/robbyrussell/oh-my-zsh.git dest=~/.oh-my-zsh

- name: copy .zshrc
  copy: src=.zshrc dest=~/.zshrc

- name: copy myagnoster theme
  copy: src=myagnoster.zsh-theme dest=~/.oh-my-zsh/themes/myagnoster.zsh-theme

- name: change default shell to zsh
  user: name=nicolas shell=/bin/zsh
  become: yes
