- name: Add Docker repository key
  apt_key: id={{ apt_key_sig }} keyserver={{ apt_key_url }} state=present

- name: Add Docker repository
  apt_repository: repo='deb {{ apt_repository }} {{ ansible_distribution | lower }}-{{ ansible_distribution_release }} main' state=present update_cache=no

- name: Remove and purge lxc-docker
  apt: name=lxc-docker state=absent purge=yes
  when: remove_lxc_docker_package

- name: apt-get update
  apt: update_cache=yes

- name: Add prerequisite and docker packages
  apt: name={{ item }} state=present
  with_items:
    - apparmor
    - linux-image-extra-{{ ansible_kernel }}
    - docker-engine
    - python-dev
    - python-setuptools

- name: Start docker service
  service: name=docker state=started

- name: Install pip
  easy_install: name=pip state=present

- name: Install docker-py
  pip: name=docker-py state=present

- name: Test docker is working
  shell: docker run --rm hello-world
  changed_when: false
